### ISSUE TITLE
Preferences -> Advanced -> Default Client => Adium Crash

### ISSUE THREAD

**Issue by heavygale** [shtrom/Lurch4Adium#1]
First of all thanks for bringing carbons and omemo to adium, wich is a huge step forward for the sadly kind of dead adium. 🙂👍

I immediately installed the plugin to test it and stumbled over a crash in the preferences after installing the plugin: When accessing the "Default Client" page in the preferences Adium instantly crashes.
Preferences -> Advanced -> Default Client => Adium Crash

**EDIT:** I'm sorry,... I used Adium Version 1.5.10.3b1 and the issue got fixed in 1.5.10.4. (Looks like the updater is/was broken, as it didn't report the new Version,.. maybe because several of the Adium Websites are broken.)

**Comment by heavygale** [comment]
I am sorry,... false alert. 😳

**Comment by shtrom** [comment]
Hey, no worries.

Thanks for the report anyway. I just succintly tested, as I only use OS X when I have to, that is, at work.

Keen to here that it works, or what doesn't.

And, yeah, Adium does look pretty dead right now ):
