### ISSUE TITLE
Adium mercurial server is dead...thus no builds

### ISSUE THREAD

**Issue by lenucksi** [shtrom/Lurch4Adium#3]
So I wanted to try out your nice contribution only to find that Adium's Mercurial servers which are used in your build script are dead (503).

Are there any other Adium source locations you could try to integrate there?
Maybe that would also allow to put in a Travis Script and enable you to provide compiled builds?

**Comment by lenucksi** [comment]
Looks like there are two potential alternative repos to be used:
- https://bitbucket.org/adium/adium  (Mercurial)
- https://github.com/adium/adium (Git)

**Comment by shtrom** [comment]
I noticed that yesterday, too. Not sure what's happening there.

I have a tentative branch at https://github.com/shtrom/Lurch4Adium/tree/gh-adium that uses the GitHub mirror as a submodule, but it doesn't seem to have 1.5.10.4 tagged, nor even a mirror of some of the commits that I looked for in there.

Thanks for the BitBucket mirror, it seems to be in a better shape. Can you try this branch https://github.com/shtrom/Lurch4Adium/tree/bb-adium and let me know how you go?

If you don't care too much about building (though I can perfectly understand and applaud that you do), there is a zip file in the releases.

**Comment by lenucksi** [comment]
The branched version seems to have worked. 👍

**Comment by RobFog** [comment]
The server is back up… 🙂
