### ISSUE TITLE
Nothing seems to be working

### ISSUE THREAD

**Issue by irfus** [shtrom/Lurch4Adium#5]
I installed the plugin, restarted Adium (v1.5.11b3). No output from either `/carbons on` or `/lurch help`.  Those actually end up being transmitted to the recipient in the clear. Neither carbons functionality nor omemo encryption is functionally working.

**Comment by shtrom** [comment]
Hum, does the plugin show up in `Adium`/`Xtras Manager`, in the `Plugins` section? I assume you are using the released build?

Do you get anything in the debug log file (start Adium then keep `Alt`/`Option` pressed, it will show a startup window allowing to `Start in debug mode`, from there, you should have a new `Debug Window` option in the application menu.

<img width="287" alt="screen shot 2017-07-05 at 17 23 14" src="https://user-images.githubusercontent.com/160280/27853592-aba1f2d8-61a6-11e7-98f8-25525580df19.png">

Can you filter the log by `lurch` and `carbons` and show us what's there? There should be some messages when you connect.

**Comment by irfus** [comment]
Plugin shows up in the Xtras Manager. Filtering the debug log for lurch/carbons shows nothing.

BTW, I had the same experience when I tried to wrap lurch as an Adium Plugin myself a few weeks ago, just assumed I'd done something wrong entirely. 

Edit: Released build, yes.

**Comment by irfus** [comment]
Completely removing all Adium related files and reinstalling the latest beta (1.5.10.3b3 ; what is up with Adium's versioning?!) with the plugin is working.
