### ISSUE TITLE
/lurch enable

### ISSUE THREAD

**Issue by splurched** [shtrom/Lurch4Adium#7]
in texting window output:

`Valid arguments for 'lurch' in IMs are 'show', 'remove', 'blacklist', 'uninstall', and 'help'.`

I am texting with an android user of Conversations - very OMEMO capable.  I can view fp conv and own id and fp own

v 1.5.10.4

**Comment by shtrom** [comment]
I think `/lurch enable` is only for groupchats https://github.com/gkdr/lurch#usage

If the fps are shown, you should be fine. Double check with the Conversations user, they will be able to tell you if encryption is on or not.

It's not awesome at the moment, as there is no clear indication on the Adium side (see #6), but I haven't had time to investigate yet.

I'll close the issue for the moment, but feel free to reopen if your Conversations-using contact does not see an encrypted communication.

**Comment by vitich** [comment]
No! Not working... I can read conversation logs on my ejabberd server!
