### ISSUE TITLE
Carbons4Adium?

### ISSUE THREAD

**Issue by arahlin** [shtrom/Lurch4Adium#8]
Is it possible to make a version of this plugin that includes just carbons?  I have a use case in which I would like the functionality of carbons without requiring lurch, and I don't see a way to disable OMEMO by default (while still enabling carbons) with this plugin as written.

**Comment by bolasblack** [comment]
Hi, I think you can send `/lurch blacklist add` in the conversation window to disable lurch functional and still can enable carbons.

**Comment by shtrom** [comment]
I'll close this one for now (see comment on #9). Please reopen if you fell it's still an issue.
